### ISSUE TITLE
ESPHOME Linking Error

### ISSUE THREAD

**Issue by GernotAlthammer** [maxgerhardt/platform-raspberrypi#80] opened 2024-09-29 14:09 UTC
Linking of ESPHome project does show error

**ESPHome:** 2024.9.1

**YAML configuration:**
```
esphome:
  name: pico-w-1
  friendly_name: pico-w-1

rp2040:
  board: rpipicow
  framework:
    # Required until https://github.com/platformio/platform-raspberrypi/pull/36 is merged
    platform_version: https://github.com/maxgerhardt/platform-raspberrypi.git
```
**Error-Message:**
```
Linking .pioenvs/pico-w-1/firmware.elf
/data/cache/platformio/packages/toolchain-rp2040-earlephilhower/bin/../lib/gcc/arm-none-eabi/14.2.0/../../../../arm-none-eabi/bin/ld: /data/cache/platformio/packages/toolchain-rp2040-earlephilhower/bin/../lib/gcc/arm-none-eabi/14.2.0/../../../../arm-none-eabi/lib/thumb/libc.a(libc_a-findfp.o): in function `std':
/workdir/repo/newlib/newlib/libc/stdio/findfp.c:93:(.text+0xda): undefined reference to `__retarget_lock_init_recursive'
/data/cache/platformio/packages/toolchain-rp2040-earlephilhower/bin/../lib/gcc/arm-none-eabi/14.2.0/../../../../arm-none-eabi/bin/ld: /workdir/repo/newlib/newlib/libc/stdio/findfp.c:93:(.text+0x124): undefined reference to `__retarget_lock_init_recursive'
/data/cache/platformio/packages/toolchain-rp2040-earlephilhower/bin/../lib/gcc/arm-none-eabi/14.2.0/../../../../arm-none-eabi/bin/ld: /workdir/repo/newlib/newlib/libc/stdio/findfp.c:93:(.text+0x17c): undefined reference to `__retarget_lock_init_recursive'
/data/cache/platformio/packages/toolchain-rp2040-earlephilhower/bin/../lib/gcc/arm-none-eabi/14.2.0/../../../../arm-none-eabi/bin/ld: /data/cache/platformio/packages/toolchain-rp2040-earlephilhower/bin/../lib/gcc/arm-none-eabi/14.2.0/../../../../arm-none-eabi/lib/thumb/libc.a(libc_a-findfp.o): in function `__sfp':
/workdir/repo/newlib/newlib/libc/stdio/findfp.c:201:(.text+0x1ea): undefined reference to `__retarget_lock_init_recursive'
collect2: error: ld returned 1 exit status
```

**Comment by maxgerhardt** [comment] 2024-09-29 20:37
Don't use the bleeding edge platform version with an old Arduino-Pico version. Fixate both in place. Duplicate of #75, #79, https://github.com/earlephilhower/arduino-pico/issues/2502

**Closed as completed by maxgerhardt** 2024-09-29 20:37 UTC

**Comment by maxgerhardt** [comment] 2024-09-29 20:38
To be specific: 

Replace
```yaml
rp2040:
  board: rpipicow
  framework:
    # Required until https://github.com/platformio/platform-raspberrypi/pull/36 is merged
    platform_version: https://github.com/maxgerhardt/platform-raspberrypi.git
```
with
```yaml
rp2040:
  board: rpipicow
  framework:
    # Required until https://github.com/platformio/platform-raspberrypi/pull/36 is merged
    platform_version: https://github.com/maxgerhardt/platform-raspberrypi.git#5e87ae34ca025274df25b3303e9e9cb6c120123c
```

**Comment by GernotAlthammer** [comment] 2024-09-29 20:51
Danke Maximilian. Firmware build ist ohne Fehler durchgelaufen :)

**Comment by maxgerhardt** [comment] 2024-09-30 16:06
FYI we've switched back to mainline Arduino-Pico, so the latest `https://github.com/maxgerhardt/platform-raspberrypi.git` works again with `https://github.com/earlephilhower/arduino-pico.git`.

If ESPHome is selecting an commit of Arduino-Pico though, you still need the older platform per above. I'm thinking about detecting the older Arduino-Pico version and using the correct older toolchain with it, aka adding backwards compatibility.

**Comment by GernotAlthammer** [comment] 2024-10-01 21:02
Hi Maximilian,
the ESPHome 2024.9.2 does fix the "behind the scenes stuff" for the users.
See ESPHome RP2040 update and recommendations:
https://esphome.io/components/rp2040.html
